# https://github.com/netlify/build/issues/1633#issuecomment-941965924
# https://github.com/vitejs/vite/blob/main/netlify.toml#L3
[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = "dist/"

  # -- Netlify Error --
  # Lockfile is up-to-date, resolution step is skipped
  # ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with packages/myers-diff/package.json

  # add '--no-frozen-lockfile' in the install process to solve error
  command = "npx pnpm i --store=node_modules/.pnpm-store --no-frozen-lockfile && npx pnpm build"